packages:
  - 'packages/*'
  - 'scripts/deployments'

allowBuilds:
  esbuild: false
  unrs-resolver: false
  workerd: false

minimumReleaseAgeExclude:
  - cf@1.0.0-beta.6
  - miniflare@5.20260926.1-alpha
  - wrangler@4.144.0

minimumReleaseAgeExcludePrune: true
