'use strict';

import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import { SCHEMA_FILENAME } from './constants.mjs';
import { BASE_URL } from '../../constants.mjs';
import { generateJsonSchema } from './util/generateJsonSchema.mjs';

/**
 * This generator is responsible for collecting the JSON output generated by
 * the `json` generator into a single JSON file.
 *
 * @typedef {Array<ApiDocMetadataEntry>} Input
 *
 * @type {GeneratorMetadata<Input, object>}
 */
export default {
  name: 'json-all',

  // This should be kept in sync with the JSON schema version for this
  // generator AND the `json` generator
  version: '2.0.0',

  description:
    'This generator is responsible for collecting the JSON output generated by the `json` generator into a single JSON file.',

  dependsOn: 'json',

  /**
   * Generates a JSON file.
   *
   * @param {Input} input
   * @param {Partial<GeneratorOptions>} param1
   * @returns {Promise<object>}
   */
  async generate(input, { version, output }) {
    const versionString = `v${version.toString()}`;

    const generatedValue = {
      $schema: `${BASE_URL}docs/${versionString}/api/${SCHEMA_FILENAME}`,
      modules: [],
      text: [],
    };

    const propertiesToIgnore = ['$schema', 'source'];

    input.forEach(section => {
      const copiedSection = {};

      Object.keys(section).forEach(key => {
        if (!propertiesToIgnore.includes(key)) {
          copiedSection[key] = section[key];
        }
      });

      switch (section.type) {
        case 'module':
          generatedValue.modules.push(copiedSection);
          break;
        case 'text':
          generatedValue.text.push(copiedSection);
          break;
        default:
          throw new TypeError(`unsupported root section type ${section.type}`);
      }
    });

    if (output) {
      const schema = generateJsonSchema(versionString);

      // Write the parsed JSON schema to the output directory
      await writeFile(join(output, SCHEMA_FILENAME), JSON.stringify(schema));
    }

    return generatedValue;
  },
};
