import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import { loadGenerator } from '@doc-kit/core/generators/loader.mjs';
import { loadMarkdownPlugins } from '@doc-kit/core/utils/markdown/plugins.mjs';
import { u } from 'unist-builder';

import { buildPages } from '../buildPages.mjs';

// Pages are serialised with the pipeline of `llms-txt-full`
await loadMarkdownPlugins(
  await loadGenerator(import.meta.resolve('../../index.mjs'))
);

const entry = (path, text, extra = {}) => ({
  path,
  content: u('root', [u('paragraph', [u('text', text)])]),
  ...extra,
});

describe('buildPages', () => {
  it('joins the content of the entries of each page, in order', () => {
    const pages = buildPages([
      entry('/a', 'First.'),
      entry('/b', 'Other.'),
      entry('/a', 'Second.'),
    ]);

    assert.deepEqual(pages, [
      { path: '/a', markdown: 'First.\n\nSecond.\n' },
      { path: '/b', markdown: 'Other.\n' },
    ]);
  });

  it('serialises type annotations back to Markdown', () => {
    const content = u('root', [
      u('paragraph', [
        u('text', 'Returns a '),
        u('typeAnnotation', { value: 'Promise<string>' }),
        u('text', '.'),
      ]),
    ]);

    assert.deepEqual(buildPages([{ path: '/a', content }]), [
      { path: '/a', markdown: 'Returns a {Promise<string>}.\n' },
    ]);
  });

  it('serialises the JSX of MDX pages', () => {
    const content = u('root', [
      u('mdxJsxFlowElement', { name: 'Foo', attributes: [] }, []),
    ]);

    assert.deepEqual(buildPages([{ path: '/a', content, mdx: true }]), [
      { path: '/a', markdown: '<Foo />\n' },
    ]);
  });

  it('leaves out pages generated by other generators', () => {
    assert.deepEqual(
      buildPages([entry('/all', 'All.', { synthetic: true })]),
      []
    );
  });
});
