import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import { u } from 'unist-builder';

import { buildPages } from '../buildPages.mjs';

const entry = (path, text, extra = {}) => ({
  path,
  content: u('root', [u('paragraph', [u('text', text)])]),
  ...extra,
});

describe('buildPages', () => {
  it('joins the content of the entries of each page, in order', () => {
    const pages = buildPages([
      entry('/a', 'First.'),
      entry('/b', 'Other.'),
      entry('/a', 'Second.'),
    ]);

    assert.deepEqual(pages, [
      { path: '/a', markdown: 'First.\n\nSecond.\n' },
      { path: '/b', markdown: 'Other.\n' },
    ]);
  });

  it('leaves out pages generated by other generators', () => {
    assert.deepEqual(
      buildPages([entry('/all', 'All.', { synthetic: true })]),
      []
    );
  });
});
