# https://github.com/codespell-project/actions-codespell
name: codespell
on: [pull_request, push]
permissions:
  contents: read

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2
        with:
          ignore_words_list: crate,raison
          exclude_file: .gitignore
          skip: pnpm-lock.yaml, ./packages/core/src/generators/mandoc/template.1
