name: Documentation Site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build docs site
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: nodejs/web-team/actions/setup-environment@9f3c83af227d721768d9dbb63009a47ed4f4282f
        with:
          use-version-file: true
          pnpm: true

      - name: Build site
        run: node --run docs:build

      - name: Upload site artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: docs-site
          path: www/out
